# Generated by Django 4.0.3 on 2022-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200)),
                ('rollno', models.IntegerField(max_length=200)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
