# Generated by Django 4.0.3 on 2022-03-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_student_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('salary', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
